import { createCipheriv, createDecipheriv, createHash, createHmac } from "node:crypto";
import {
  GRANT_CODE_FORMAT_VERSION,
  GRANT_CODE_KIND,
  type GrantKeyRing,
  type GrantRandomness,
  type StoredGrantCode,
} from "@/lib/grant-types";

/**
 * Reviewed Grant-Code vocabulary artifact. The source review records the
 * operational criteria that are not expressible as a type or regex: short
 * common-English words, usable by non-native speakers, and radio-distinct
 * spelling/homophone/prefix pairs. The artifact is immutable at runtime.
 */
export const GRANT_CODE_WORD_LIST_REVIEW = Object.freeze({
  artifactVersion: "grant-code-word-list-v1",
  source:
    "Frequency-filtered English review artifact: wordfreq top-n corpus, lexical exclusion review, and radio-screen validation",
  canonicalSha256: "805fae4af4d35dac1afd9f80a3bb6d9763ebc802ec9da74fb16f96a5a6602c8c",
  wordCount: 1024,
  normalizedWordCount: 1024,
  uniqueNormalizedWordCount: 1024,
  reviewedShortWords: true,
  reviewedCommonEnglish: true,
  minimumCorpusFrequency: 4.0,
  minimumWordLength: 4,
  maximumWordLength: 7,
  reviewedForNonNativeComprehension: true,
  reviewedRadioDistinct: true,
  reviewedSpelling: true,
  reviewedHomophones: true,
  reviewedPrefixConfusability: true,
  radioConfusablePairs: 0,
  homophonePairs: 0,
  prefixAmbiguities: 0,
});

/**
 * Versioned human-reviewed exclusion artifact. Each group contains words
 * that must not coexist in the spoken Grant-Code vocabulary. The groups also
 * retain reviewed counterparts that are intentionally excluded from the
 * chosen vocabulary, making the review boundary auditable instead of
 * inferring homophones from spelling alone.
 */
export const GRANT_CODE_REVIEWED_CONFUSABLE_GROUPS = Object.freeze([
  Object.freeze(["accept", "except"]),
  Object.freeze(["advice", "advise"]),
  Object.freeze(["affect", "effect"]),
  Object.freeze(["ate", "eight"]),
  Object.freeze(["brake", "break"]),
  Object.freeze(["cell", "sell"]),
  Object.freeze(["coarse", "course"]),
  Object.freeze(["days", "daze"]),
  Object.freeze(["great", "grate"]),
  Object.freeze(["hole", "whole"]),
  Object.freeze(["mail", "male"]),
  Object.freeze(["meat", "meet"]),
  Object.freeze(["miner", "minor"]),
  Object.freeze(["peace", "piece"]),
  Object.freeze(["role", "roll"]),
  Object.freeze(["scene", "seen"]),
  Object.freeze(["sight", "site"]),
  Object.freeze(["sole", "soul"]),
  Object.freeze(["steal", "steel"]),
  Object.freeze(["suite", "sweet"]),
  Object.freeze(["than", "then"]),
  Object.freeze(["their", "there"]),
  Object.freeze(["through", "threw"]),
  Object.freeze(["taught", "taut"]),
  Object.freeze(["troops", "troupe"]),
  Object.freeze(["wait", "weight"]),
  Object.freeze(["waive", "wave"]),
  Object.freeze(["wear", "where"]),
  Object.freeze(["weather", "whether"]),
  Object.freeze(["weak", "week"]),
  Object.freeze(["wood", "would"]),
]);

export const GRANT_CODE_CONFUSABILITY_REVIEW = Object.freeze({
  artifactVersion: "grant-code-confusability-review-v1",
  groupCount: 31,
  canonicalSha256: "97c8140c8ac6d5db78ee40291d36021696eff6e0a41ebee507ef9d6fc28affb3",
});

export const GRANT_CODE_WORDS = Object.freeze([
  "that",
  "with",
  "this",
  "have",
  "from",
  "your",
  "they",
  "just",
  "like",
  "about",
  "what",
  "when",
  "more",
  "were",
  "their",
  "which",
  "time",
  "been",
  "would",
  "people",
  "some",
  "also",
  "them",
  "than",
  "good",
  "only",
  "after",
  "first",
  "into",
  "know",
  "make",
  "over",
  "could",
  "back",
  "want",
  "because",
  "well",
  "said",
  "most",
  "much",
  "very",
  "where",
  "even",
  "should",
  "here",
  "need",
  "really",
  "right",
  "work",
  "years",
  "being",
  "going",
  "before",
  "made",
  "still",
  "take",
  "many",
  "never",
  "life",
  "world",
  "down",
  "great",
  "through",
  "last",
  "while",
  "best",
  "such",
  "love",
  "home",
  "long",
  "both",
  "come",
  "state",
  "around",
  "between",
  "always",
  "better",
  "find",
  "help",
  "high",
  "little",
  "since",
  "another",
  "does",
  "things",
  "under",
  "during",
  "game",
  "give",
  "house",
  "place",
  "school",
  "again",
  "next",
  "each",
  "show",
  "feel",
  "sure",
  "family",
  "keep",
  "might",
  "please",
  "free",
  "second",
  "away",
  "left",
  "number",
  "city",
  "days",
  "name",
  "night",
  "play",
  "until",
  "company",
  "doing",
  "called",
  "having",
  "thought",
  "done",
  "however",
  "getting",
  "group",
  "looking",
  "public",
  "women",
  "care",
  "start",
  "system",
  "week",
  "already",
  "nothing",
  "person",
  "today",
  "change",
  "enough",
  "full",
  "making",
  "point",
  "read",
  "told",
  "hard",
  "mean",
  "once",
  "support",
  "tell",
  "music",
  "power",
  "belong",
  "stop",
  "water",
  "based",
  "believe",
  "head",
  "small",
  "later",
  "less",
  "line",
  "order",
  "party",
  "says",
  "service",
  "country",
  "open",
  "season",
  "general",
  "united",
  "using",
  "area",
  "black",
  "face",
  "five",
  "kind",
  "maybe",
  "story",
  "course",
  "health",
  "hope",
  "news",
  "able",
  "book",
  "early",
  "friends",
  "local",
  "post",
  "video",
  "young",
  "others",
  "social",
  "talk",
  "court",
  "fact",
  "guys",
  "half",
  "hand",
  "level",
  "mind",
  "often",
  "single",
  "become",
  "body",
  "coming",
  "control",
  "food",
  "hours",
  "office",
  "problem",
  "south",
  "true",
  "almost",
  "history",
  "large",
  "room",
  "several",
  "taking",
  "wrong",
  "anyone",
  "girl",
  "matter",
  "pretty",
  "saying",
  "yeah",
  "class",
  "close",
  "idea",
  "looks",
  "cause",
  "happy",
  "human",
  "members",
  "months",
  "move",
  "series",
  "empty",
  "data",
  "north",
  "special",
  "watch",
  "light",
  "million",
  "morning",
  "short",
  "stay",
  "deal",
  "rather",
  "reason",
  "report",
  "third",
  "turn",
  "whether",
  "among",
  "check",
  "further",
  "heart",
  "minutes",
  "myself",
  "asked",
  "child",
  "living",
  "phone",
  "behind",
  "easy",
  "gonna",
  "market",
  "near",
  "plan",
  "quite",
  "west",
  "final",
  "former",
  "front",
  "kids",
  "bring",
  "college",
  "current",
  "example",
  "meet",
  "program",
  "type",
  "baby",
  "chance",
  "father",
  "process",
  "study",
  "word",
  "across",
  "action",
  "clear",
  "gets",
  "himself",
  "outside",
  "self",
  "board",
  "cost",
  "field",
  "held",
  "instead",
  "moment",
  "mother",
  "seems",
  "town",
  "energy",
  "fight",
  "fine",
  "force",
  "issue",
  "rest",
  "results",
  "running",
  "summer",
  "term",
  "wife",
  "goes",
  "land",
  "miss",
  "project",
  "shot",
  "site",
  "strong",
  "account",
  "eyes",
  "include",
  "parents",
  "period",
  "record",
  "similar",
  "total",
  "above",
  "club",
  "common",
  "died",
  "film",
  "lead",
  "perfect",
  "share",
  "center",
  "county",
  "couple",
  "english",
  "happen",
  "inside",
  "online",
  "private",
  "return",
  "sense",
  "test",
  "view",
  "break",
  "middle",
  "present",
  "sorry",
  "wish",
  "answer",
  "design",
  "gold",
  "guess",
  "learn",
  "policy",
  "society",
  "added",
  "average",
  "bank",
  "brought",
  "certain",
  "church",
  "medical",
  "park",
  "press",
  "rough",
  "sent",
  "tried",
  "worth",
  "cool",
  "exactly",
  "giving",
  "ground",
  "provide",
  "sound",
  "source",
  "usually",
  "value",
  "follow",
  "lives",
  "rate",
  "save",
  "stand",
  "stuff",
  "amount",
  "drive",
  "fast",
  "federal",
  "felt",
  "green",
  "league",
  "match",
  "model",
  "picture",
  "size",
  "trust",
  "forward",
  "paid",
  "range",
  "review",
  "science",
  "various",
  "brother",
  "cannot",
  "chief",
  "hate",
  "looked",
  "lower",
  "natural",
  "quality",
  "style",
  "vote",
  "amazing",
  "blood",
  "itself",
  "related",
  "stage",
  "article",
  "attack",
  "born",
  "decided",
  "enjoy",
  "entire",
  "perhaps",
  "poor",
  "release",
  "website",
  "written",
  "choice",
  "code",
  "council",
  "cover",
  "door",
  "foreign",
  "legal",
  "pick",
  "race",
  "seven",
  "sign",
  "simple",
  "simply",
  "super",
  "union",
  "walk",
  "began",
  "built",
  "crazy",
  "daily",
  "figure",
  "modern",
  "ones",
  "paper",
  "parts",
  "popular",
  "safe",
  "version",
  "voice",
  "whose",
  "writing",
  "army",
  "earth",
  "forget",
  "goal",
  "huge",
  "listen",
  "okay",
  "success",
  "towards",
  "ways",
  "access",
  "below",
  "created",
  "deep",
  "offer",
  "pass",
  "risk",
  "sleep",
  "table",
  "truth",
  "ball",
  "card",
  "cases",
  "dark",
  "europe",
  "percent",
  "piece",
  "recent",
  "visit",
  "wanna",
  "wrote",
  "allowed",
  "boys",
  "culture",
  "fans",
  "growth",
  "married",
  "respect",
  "river",
  "rock",
  "shall",
  "speak",
  "tonight",
  "album",
  "charge",
  "effect",
  "eight",
  "except",
  "funny",
  "limited",
  "moving",
  "network",
  "sales",
  "spent",
  "store",
  "student",
  "track",
  "weight",
  "brown",
  "capital",
  "double",
  "expect",
  "island",
  "normal",
  "station",
  "text",
  "content",
  "credit",
  "despite",
  "female",
  "focus",
  "husband",
  "join",
  "kept",
  "message",
  "quickly",
  "region",
  "section",
  "sort",
  "speed",
  "travel",
  "contact",
  "drop",
  "feet",
  "link",
  "welcome",
  "beyond",
  "earlier",
  "extra",
  "jobs",
  "sharp",
  "studies",
  "unless",
  "winning",
  "agree",
  "clean",
  "episode",
  "income",
  "manager",
  "photo",
  "scene",
  "sold",
  "spend",
  "teams",
  "ability",
  "asking",
  "calling",
  "coach",
  "heavy",
  "search",
  "subject",
  "wide",
  "claim",
  "global",
  "gotta",
  "hotel",
  "lady",
  "letter",
  "nobody",
  "product",
  "regular",
  "sister",
  "stories",
  "annual",
  "anymore",
  "battle",
  "degree",
  "floor",
  "france",
  "growing",
  "image",
  "opinion",
  "reach",
  "sports",
  "active",
  "biggest",
  "civil",
  "dance",
  "defense",
  "master",
  "ship",
  "stock",
  "wonder",
  "worst",
  "awesome",
  "band",
  "beach",
  "cash",
  "effort",
  "ended",
  "imagine",
  "impact",
  "lack",
  "latest",
  "older",
  "protect",
  "secret",
  "senior",
  "spring",
  "address",
  "anyway",
  "bought",
  "calls",
  "choose",
  "details",
  "direct",
  "dream",
  "easily",
  "finish",
  "skin",
  "sweet",
  "touch",
  "caught",
  "damage",
  "disease",
  "doctor",
  "doubt",
  "drink",
  "driving",
  "fish",
  "machine",
  "notice",
  "trip",
  "basic",
  "captain",
  "carry",
  "crime",
  "explain",
  "holding",
  "laws",
  "male",
  "reality",
  "spot",
  "winter",
  "worse",
  "advice",
  "broken",
  "comment",
  "holy",
  "lived",
  "lots",
  "nation",
  "prices",
  "primary",
  "purpose",
  "sick",
  "teacher",
  "theory",
  "agency",
  "camera",
  "catch",
  "cell",
  "economy",
  "hall",
  "status",
  "trial",
  "truly",
  "zebra",
  "coffee",
  "complex",
  "flight",
  "library",
  "located",
  "putting",
  "queen",
  "sitting",
  "smooth",
  "actual",
  "attempt",
  "channel",
  "eating",
  "glass",
  "losing",
  "mobile",
  "prior",
  "receive",
  "royal",
  "screen",
  "serve",
  "slow",
  "species",
  "speech",
  "traffic",
  "whom",
  "animals",
  "appears",
  "bottom",
  "cities",
  "demand",
  "engine",
  "famous",
  "notes",
  "partner",
  "raised",
  "runs",
  "songs",
  "square",
  "twice",
  "wind",
  "worry",
  "brand",
  "digital",
  "fourth",
  "fresh",
  "mental",
  "mouth",
  "owner",
  "realize",
  "remain",
  "score",
  "smart",
  "surface",
  "throw",
  "wedding",
  "acting",
  "arms",
  "benefit",
  "budget",
  "click",
  "faith",
  "fashion",
  "hearing",
  "metal",
  "profile",
  "pull",
  "push",
  "rose",
  "seemed",
  "target",
  "village",
  "agent",
  "apply",
  "basis",
  "draw",
  "memory",
  "prime",
  "silver",
  "soul",
  "spread",
  "supply",
  "adult",
  "artist",
  "edition",
  "grade",
  "method",
  "option",
  "stone",
  "winner",
  "arrived",
  "camp",
  "correct",
  "improve",
  "movies",
  "prevent",
  "removed",
  "spirit",
  "trouble",
  "apart",
  "dinner",
  "dollars",
  "eastern",
  "fifth",
  "gift",
  "herself",
  "produce",
  "require",
  "thinks",
  "birth",
  "bridge",
  "carried",
  "concept",
  "copy",
  "dogs",
  "garden",
  "host",
  "housing",
  "journal",
  "labor",
  "length",
  "lucky",
  "patient",
  "prove",
  "rare",
  "skills",
  "tough",
  "balance",
  "dress",
  "magic",
  "managed",
  "request",
  "vehicle",
  "volume",
  "beauty",
  "billion",
  "busy",
  "buying",
  "corner",
  "develop",
  "ends",
  "paying",
  "roll",
  "suggest",
  "treat",
  "unique",
  "variety",
  "youth",
  "bigger",
  "dont",
  "edge",
  "excited",
  "forever",
  "funds",
  "injury",
  "iron",
  "wine",
  "angeles",
  "blog",
  "exist",
  "forms",
  "honest",
  "mention",
  "nuclear",
  "reduce",
  "sides",
  "spanish",
  "steps",
  "stress",
  "victory",
  "clothes",
  "entered",
  "kick",
  "massive",
  "plenty",
  "prince",
  "proper",
  "quarter",
  "session",
  "useful",
  "valley",
  "willing",
  "zone",
  "awards",
  "bear",
  "cheap",
  "climate",
  "duty",
  "flying",
  "hundred",
  "museum",
  "path",
  "promise",
  "steel",
  "warm",
  "afraid",
  "arts",
  "border",
  "command",
  "crew",
  "crowd",
  "dating",
  "enemy",
  "ensure",
  "filled",
  "fixed",
  "ocean",
  "profit",
  "proof",
  "wins",
  "bodies",
  "chair",
  "grew",
  "honor",
  "jump",
  "launch",
  "listed",
  "minimum",
  "native",
  "sets",
  "supreme",
  "survey",
  "trees",
  "update",
  "writer",
  "yellow",
  "ancient",
  "ending",
  "express",
  "flow",
  "formed",
  "illegal",
  "joke",
  "soft",
  "sugar",
  "taught",
  "adding",
  "affairs",
  "allows",
  "applied",
  "entry",
  "grown",
  "hoping",
  "lawyer",
  "legs",
  "lying",
  "mistake",
  "pool",
  "shoes",
  "smoke",
  "squad",
  "angry",
  "concern",
  "discuss",
  "falling",
  "hole",
  "holiday",
  "laugh",
  "liberal",
  "milk",
  "payment",
  "perform",
  "sector",
  "sharing",
  "snow",
  "storm",
  "streets",
  "strike",
  "studio",
  "actor",
  "advance",
  "chain",
  "chapter",
  "cook",
  "cute",
  "equal",
  "fake",
  "finance",
  "hits",
  "journey",
  "kitchen",
  "measure",
  "split",
  "task",
  "taxes",
  "twenty",
  "urban",
  "escape",
  "ladies",
  "mixed",
  "phase",
  "revenue",
  "smile",
  "talent",
  "troops",
  "besides",
  "blame",
  "bowl",
  "chicken",
  "context",
  "display",
  "dying",
  "falls",
  "false",
  "funding",
  "neck",
  "novel",
  "obvious",
  "stadium",
  "surgery",
  "trading",
  "tuesday",
  "vision",
  "worried",
  "zero",
  "begins",
  "editor",
  "jail",
  "kingdom",
  "mayor",
  "minor",
  "pages",
  "serving",
  "suicide",
  "tiny",
  "voting",
  "walls",
  "wave",
  "alcohol",
  "capable",
  "chosen",
  "cutting",
  "desire",
  "draft",
  "granted",
  "guilty",
  "jewish",
  "medium",
  "ohio",
  "seek",
  "sending",
  "ticket",
  "unable",
  "wing",
  "birds",
]);

export type GrantCodeBinding = {
  environmentId: string;
  grantId: string;
  grantType: string;
  grantVersion: string;
  scope: unknown;
};

export function normalizeGrantCode(value: unknown): string | null {
  if (typeof value !== "string" || value.length > 128) return null;
  const parts = value
    .normalize("NFKC")
    .trim()
    .toLocaleLowerCase("en-US")
    .split(/[\s_-]+/u);
  if (parts.length !== 3) return null;
  const first = parts[0];
  const second = parts[1];
  const digits = parts[2];
  if (
    first === undefined ||
    second === undefined ||
    digits === undefined ||
    !isGrantCodeWord(first) ||
    !isGrantCodeWord(second) ||
    !/^\d{3}$/u.test(digits)
  )
    return null;
  return first + "-" + second + "-" + digits;
}

export function generateGrantCode(randomness: GrantRandomness): string {
  for (let attempt = 0; attempt < 32; attempt += 1) {
    const bytes = randomness.bytes(6);
    if (bytes.byteLength !== 6)
      throw new Error("Injected Grant-Code randomness has an invalid size.");
    const left = GRANT_CODE_WORDS[((bytes[0] ?? 0) & 0x03) * 256 + (bytes[1] ?? 0)];
    const right = GRANT_CODE_WORDS[((bytes[2] ?? 0) & 0x03) * 256 + (bytes[3] ?? 0)];
    const digitsValue = (bytes[4] ?? 0) * 256 + (bytes[5] ?? 0);
    if (left === undefined || right === undefined || left === right || digitsValue >= 65_000)
      continue;
    return left + "-" + right + "-" + String(digitsValue % 1_000).padStart(3, "0");
  }
  throw new Error("Grant-Code randomness could not produce a distinct unbiased code.");
}

export function validateGrantCodeConfusabilityArtifact(
  candidateWords: readonly string[] = GRANT_CODE_WORDS,
): string | null {
  if (
    GRANT_CODE_REVIEWED_CONFUSABLE_GROUPS.length !== GRANT_CODE_CONFUSABILITY_REVIEW.groupCount ||
    createHash("sha256")
      .update(JSON.stringify(GRANT_CODE_REVIEWED_CONFUSABLE_GROUPS), "utf8")
      .digest("hex") !== GRANT_CODE_CONFUSABILITY_REVIEW.canonicalSha256
  )
    return "Grant-Code confusability artifact does not match its reviewed digest.";

  const selected = new Set(
    candidateWords.map((word) => word.normalize("NFKC").toLocaleLowerCase("en-US")),
  );
  for (const group of GRANT_CODE_REVIEWED_CONFUSABLE_GROUPS) {
    const selectedGroupWords = group.filter((word) => selected.has(word));
    if (selectedGroupWords.length > 1)
      return `Grant-Code vocabulary contains a reviewed confusable group: ${group.join("/")}.`;
  }
  return null;
}

export function validateGrantCodeWordList(
  candidateWords: readonly string[] = GRANT_CODE_WORDS,
): string | null {
  if (
    candidateWords.length !== 1024 ||
    GRANT_CODE_WORD_LIST_REVIEW.wordCount !== 1024 ||
    GRANT_CODE_WORD_LIST_REVIEW.normalizedWordCount !== 1024 ||
    GRANT_CODE_WORD_LIST_REVIEW.uniqueNormalizedWordCount !== 1024 ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedShortWords !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedCommonEnglish !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedForNonNativeComprehension !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedRadioDistinct !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedSpelling !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedHomophones !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.reviewedPrefixConfusability !== true ||
    GRANT_CODE_WORD_LIST_REVIEW.radioConfusablePairs !== 0 ||
    GRANT_CODE_WORD_LIST_REVIEW.homophonePairs !== 0 ||
    GRANT_CODE_WORD_LIST_REVIEW.prefixAmbiguities !== 0
  )
    return "Grant-Code word list must contain exactly 1,024 words.";
  const words = new Set<string>();
  const normalizedWords = new Set<string>();
  for (const word of candidateWords) {
    const normalized = word.normalize("NFKC").toLocaleLowerCase("en-US");
    if (
      normalized !== word ||
      !/^[a-z]{4,7}$/u.test(normalized) ||
      words.has(word) ||
      normalizedWords.has(normalized)
    )
      return "Grant-Code word list contains an invalid or duplicate word.";
    words.add(word);
    normalizedWords.add(normalized);
  }
  if (
    normalizedWords.size !== GRANT_CODE_WORD_LIST_REVIEW.uniqueNormalizedWordCount ||
    (candidateWords === GRANT_CODE_WORDS &&
      createHash("sha256").update(candidateWords.join("\n"), "utf8").digest("hex") !==
        GRANT_CODE_WORD_LIST_REVIEW.canonicalSha256)
  )
    return "Grant-Code word list does not match its reviewed artifact.";
  const confusabilityError = validateGrantCodeConfusabilityArtifact(candidateWords);
  if (confusabilityError !== null) return confusabilityError;
  for (const word of words) {
    for (const other of words) {
      if (word !== other && (word.startsWith(other) || other.startsWith(word)))
        return "Grant-Code word list contains a prefix ambiguity.";
    }
  }
  const radioSignatures = new Map<string, string>();
  for (const word of words) {
    const signature = word.replace(/[aeiou]/gu, "");
    const previous = radioSignatures.get(signature);
    if (previous !== undefined && previous !== word)
      return "Grant-Code word list contains a radio-confusable pair.";
    radioSignatures.set(signature, word);
  }
  return null;
}

export function encryptGrantCode(
  code: string,
  binding: GrantCodeBinding,
  randomness: GrantRandomness,
  keyRing: GrantKeyRing,
): StoredGrantCode {
  const encryptionKeyVersion = keyRing.encryption.currentVersion;
  const encryptionKey = keyRing.encryption.keys.get(encryptionKeyVersion);
  if (encryptionKey === undefined || encryptionKey.byteLength !== 32)
    throw new Error("The Grant encryption key is unavailable.");
  const iv = randomness.bytes(12);
  if (iv.byteLength !== 12)
    throw new Error("Injected Grant-Code IV randomness has an invalid size.");
  const cipher = createCipheriv("aes-256-gcm", encryptionKey, iv);
  cipher.setAAD(new TextEncoder().encode(canonicalBinding(binding)));
  const ciphertext = Buffer.concat([cipher.update(code, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  const lookupKeyVersion = keyRing.audit.currentVersion;
  const lookupKey = keyRing.audit.keys.get(lookupKeyVersion);
  if (lookupKey === undefined || lookupKey.byteLength < 32)
    throw new Error("The stable Grant-Code lookup key is unavailable.");
  const lookupDigest = encode(hmac(lookupKey, "grant-code-lookup:" + code));
  return {
    state: "present",
    formatVersion: GRANT_CODE_FORMAT_VERSION,
    kind: GRANT_CODE_KIND,
    encryptionKeyVersion,
    lookupKeyVersion,
    iv: encode(iv),
    ciphertext: encode(ciphertext),
    tag: encode(tag),
    lookupDigest,
    fingerprint: encode(hmac(lookupKey, "grant-code-fingerprint:" + code)),
  };
}

export function decryptGrantCode(
  stored: StoredGrantCode,
  binding: GrantCodeBinding,
  keyRing: GrantKeyRing,
): string | null {
  if (
    stored.state !== "present" ||
    stored.formatVersion !== GRANT_CODE_FORMAT_VERSION ||
    stored.kind !== GRANT_CODE_KIND ||
    stored.encryptionKeyVersion === null ||
    stored.lookupKeyVersion === null ||
    stored.iv === null ||
    stored.ciphertext === null ||
    stored.tag === null ||
    stored.lookupDigest === null
  )
    return null;
  const encryptionKey = keyRing.encryption.keys.get(stored.encryptionKeyVersion);
  if (encryptionKey === undefined || encryptionKey.byteLength !== 32) return null;
  try {
    const decipher = createDecipheriv("aes-256-gcm", encryptionKey, decode(stored.iv), {
      authTagLength: 16,
    });
    decipher.setAAD(new TextEncoder().encode(canonicalBinding(binding)));
    decipher.setAuthTag(decode(stored.tag));
    const code = Buffer.concat([
      decipher.update(decode(stored.ciphertext)),
      decipher.final(),
    ]).toString("utf8");
    return normalizeGrantCode(code) === code ? code : null;
  } catch {
    return null;
  }
}

export function grantCodeLookupDigest(
  code: string,
  keyRing: GrantKeyRing,
  keyVersion = keyRing.audit.currentVersion,
): string {
  const key = keyRing.audit.keys.get(keyVersion);
  if (key === undefined || key.byteLength < 32)
    throw new Error("The stable Grant-Code lookup key is unavailable.");
  return encode(hmac(key, "grant-code-lookup:" + code));
}

export function grantCodeFingerprint(
  code: string,
  keyRing: GrantKeyRing,
  keyVersion = keyRing.audit.currentVersion,
): string {
  const key = keyRing.audit.keys.get(keyVersion);
  if (key === undefined || key.byteLength < 32)
    throw new Error("The stable Grant-Code identity key is unavailable.");
  return encode(hmac(key, "grant-code-fingerprint:" + code));
}

export function eraseGrantCode(
  stored: StoredGrantCode,
  state: "disabled" | "erased",
): StoredGrantCode {
  return {
    ...stored,
    state,
    encryptionKeyVersion: null,
    lookupKeyVersion: null,
    iv: null,
    ciphertext: null,
    tag: null,
    lookupDigest: null,
  };
}

function isGrantCodeWord(value: string): boolean {
  return (GRANT_CODE_WORDS as readonly string[]).includes(value);
}

function canonicalBinding(binding: GrantCodeBinding): string {
  return JSON.stringify({
    domain: "grant-code-v1",
    formatVersion: GRANT_CODE_FORMAT_VERSION,
    kind: GRANT_CODE_KIND,
    ...binding,
  });
}

function hmac(key: Uint8Array, value: string): Uint8Array {
  return new Uint8Array(createHmac("sha256", key).update(value, "utf8").digest());
}

function encode(value: Uint8Array): string {
  return Buffer.from(value).toString("base64url");
}

function decode(value: string): Uint8Array {
  if (!/^[A-Za-z0-9_-]+$/u.test(value)) throw new Error("Invalid encoded Grant-Code material.");
  return new Uint8Array(Buffer.from(value, "base64url"));
}
